### ISSUE TITLE
Xiaomi Chuangmi Plug V3 support

### ISSUE THREAD

**Issue by cxlwill** [syssi/xiaomiplug#10]
Yesterday Xiaomi just launched a [new version of Smart Plug with 2-slot USB](https://item.mi.com/1180800005.html). No English page yet. 
My friend got one and here's the feedback:

```
'get_power', []
'get_prop', ["on","usb_on","temperature","wifi_led"]
'set_power', ["off"]
'set_usb_on', []
'set_wifi_led', ['on']
```
![chuangmi](https://user-images.githubusercontent.com/13537549/37144579-7649c362-22f9-11e8-8cb2-303ca40b8fbc.png)
I think basic logic is the same as first generation. HA component is under test.

**Comment by syssi** [comment]
Could you provide the output of the "mirobo info" command? I would like to know the model name.

**Comment by syssi** [comment]
The python-miio call looks like this:

```
self.send("miIO.info", [])
```

**Comment by cxlwill** [comment]
The model name is `chuangmi.plug.v3`. `mirobo info` output is:

```
['fw_ver']:'1.3.0_92'
['hw_ver']:'ESP8266'
['uid']:'25180012'
['model']:'chuangmi.plug.v3'
['wifi_fw_ver']:'1.5.0-dev(7f7a714)'
```

**Comment by syssi** [comment]
Could you try to request these properties just for testing:

```
mirobo raw_command "['power', 'temperature', 'current', 'mode',  'power_consume_rate', 'wifi_led', 'power_price']"
```

**Comment by syssi** [comment]
I've implemented a basic device support: https://github.com/rytilahti/python-miio/pull/257

**Comment by syssi** [comment]
As far as python-miio 0.3.8 is released I will extend this component. Thanks for your support!

**Comment by cxlwill** [comment]
Output: 
```
device.send('get_prop', ['power', 'temperature', 'current', 'mode', 'power_consume_rate', 'wifi_led', 'power_price'])
['on', 34, None, None, None, 'on', None]`
```
Thanks for `miio` and component update~~

**Comment by syssi** [comment]
@cxlwill I would be happy if your friend could test the updated custom component! Thanks in advance!

**Comment by cxlwill** [comment]
Although you clode this issue, here's the feedback: it works like a charm~ Thanks
