### ISSUE TITLE
Xiaomi Chuangmi Wifi Plug v3 goes “Unavailable” after 5 minutes 

### ISSUE THREAD

**Issue by HatHost** [syssi/xiaomiplug#11]
It’s the new plug with 2 USB ports, model: ZNCZ03CM

When HA start it’s working great, shows all data, but after 5 minutes goes “Unavailable” until next HA restart, and same again work 5 minutes and “Unavailable”, in MiHome app it works all the time

configuration.yaml:

    switch:
      - platform: xiaomi_miio
        host: 10.0.0.1
        token: abcabcabcabcabcabcabcabc
        model: chuangmi.plug.v3

also tried without “model” line, same result

error in logs:
Got exception while fetching the state: {'code': -30001, 'message': 'Resp invalid json.'}
12:42 PM components/switch/xiaomi_miio.py (ERROR)

**Comment by syssi** [comment]
This is a bug: https://community.home-assistant.io/t/xiaomi-chuangmi-wifi-plug-v3-goes-unavailable-after-5-minutes/54087/6

**Comment by syssi** [comment]
Fixed.
