### ISSUE TITLE
acpartner v3 switch not updating correctly

### ISSUE THREAD

**Issue by mouth4war** [syssi/xiaomiplug#15]
So now turn_on and turn_off work but soon after using turn_on, the switch loses sync by going off. The actual relay is still on.

status update is not working properly.

debug log for turn_on, new state shows power off and load power shows the load so its clearly on:

```
[custom_components.switch.xiaomi_miio] Response received from plug: ['ok']
[custom_components.switch.xiaomi_miio] Got new state: <AirConditioningCompanionStatus power=off, load_power=2479, air_condition_model=00000000ffffffff00, model_format=0, device_type=0, air_condition_brand=0, air_condition_remote=4294967295, state_format=0, air_condition_configuration=0130FF00, led=True, target_temperature=255, swing_mode=SwingMode.On, fan_speed=FanSpeed.Auto, mode=OperationMode.Cool>
```

**Comment by mouth4war** [comment]
I think the library is reporting power=off. Maybe there are different attributes for power for AC mode and Plug mode.

**Comment by mouth4war** [comment]
I did enable logs and got:

[miio.protocol] Unable to decrypt, returning raw bytes: b''
[custom_components.switch.xiaomi_miio] Got new state: <AirConditioningCompanionStatus **power=off,** load_power=855, air_condition_model=00000000ffffffff00, model_format=0, device_type=0, air_condition_brand=0, air_condition_remote=4294967295, state_format=0, air_condition_configuration=01101900, led=True, target_temperature=25, swing_mode=SwingMode.On, fan_speed=FanSpeed.Medium, mode=OperationMode.Cool>

**Comment by mouth4war** [comment]
OK with your updated code, I get this after turn_on

[custom_components.switch.xiaomi_miio] Got new state: <AirConditioningCompanionStatus **power=off, power_socket=['on']**, load_power=829, air_condition_model=00000000ffffffff00, model_format=0, device_type=0, air_condition_brand=0, air_condition_remote=4294967295, state_format=0, air_condition_configuration=01101900, led=True, target_temperature=25, swing_mode=SwingMode.On, fan_speed=FanSpeed.Medium, mode=OperationMode.Cool>

**Comment by mouth4war** [comment]
turn_off:

 [custom_components.switch.xiaomi_miio] Got new state: <AirConditioningCompanionStatus **power=off, power_socket=['off']**, load_power=0, air_condition_model=00000000ffffffff00, model_format=0, device_type=0, air_condition_brand=0, air_condition_remote=4294967295, state_format=0, air_condition_configuration=01101900, led=True, target_temperature=25, swing_mode=SwingMode.On, fan_speed=FanSpeed.Medium, mode=OperationMode.Cool>

**Comment by syssi** [comment]
Perfect! This is a bug. Please update the custom component.
