### ISSUE TITLE
Xiaomi Chuangmi Plug M3 support

### ISSUE THREAD

**Issue by spectrumleap** [syssi/xiaomiplug#16]
I've had a couple of Xiaomi Chuangmi Plug M1 plugs running for a few months. I ordered a few more from the same source as my original plugs, but these are Xiaomi Chuangmi Plug M3 versions with different firmware from the M1 versions (M3 fw 1.3.0_0004). The device id shows as different to my earlier plugs when retreiving the token from the sqlite database from my iOS backup.

They look identical to the M1 plugs, but identify in Mi Home as Mi Smart Plug (Wi-Fi) Basic. The M1 plugs are identified as Mi Plug Mini.

What can I do to help have support added for this newer device? I'm running Home Assistant in a Docker container on a Synology NAS.

**Comment by syssi** [comment]
Did you try to setup the new plugs? Did the Home Assistant component provide an error? I'm looking for the model name of the new generation.

**Comment by spectrumleap** [comment]
I found a post relating to the new `chuangmi.plug.hmi205` plugs that suggested using `model: chuangmi.plug.m1` until the recent updates werepublishing. I've successfully set two of these m3 plugs up in Home Assistant using `model: chuangmi.plug.m1`. Switch and temperature functions are working.

Mi Home calls them "Mi Smart Plug (Wi-Fi) Basic", and the ZMODEL name 1234567890_mihome.sqlite is `chuangmi.plug.m3`.

Model number on the back of the plug is ZNCZ04CM.

**Comment by syssi** [comment]
Cool! I will update the component.

**Comment by Electronlibre2012** [comment]
hello,

sorry but the problem is back again :

```
Error unloading entry Prise Salon Ventilateur for xiaomi_miio

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/__init__.py", line 473, in async_unload_entry
    hass.data[DOMAIN].pop(config_entry.entry_id)
KeyError: 'b52294f74aede8792918f0be3f602870'

```
i have some and they are unavailable for hours then available for 1 hours then goes unavailable again and again.

I there a way to solved it please. It seems to have happened with HA core 2023.2.x
