### ISSUE TITLE
lumi.acpartner.v3 power consumed statistics

### ISSUE THREAD

**Issue by lingxide** [syssi/xiaomiplug#17]
Hi: Thanks for adding support to lumi.acpartner.v3! May I ask if that possible to obtain power consumed value from it?

**Comment by syssi** [comment]
The current power consumption is provided as attribute. You could use a sensor template to provide the value as sensor.

**Comment by lingxide** [comment]
> The current power consumption is provided as attribute. You could use a sensor template to provide the value as sensor.

Thanks for your reply. I am using `develop` branch and couldn't found power consume value.
Feel free to let me know if you need more information for debug.

Thanks in advance!

***
HA Version: 0.87.1

Attributes Status
```
temperature: null 
model: lumi.acpartner.v3 
load_power: 0 
friendly_name: WaterHeater
icon: mdi:power-socket
--
```

**Comment by syssi** [comment]
Is the value of `load_power` always zero?

**Comment by lingxide** [comment]
No, it is correct.

**Comment by syssi** [comment]
A value of the total power consumption isn't available. The `load_power` indicates the current power consumption. Does it answer your question?

**Comment by lingxide** [comment]
okay then... got it! many thanks!
