### ISSUE TITLE
Plug with USB port compatibility?

### ISSUE THREAD

**Issue by nutinshell** [syssi/xiaomiplug#5]
Enhance with USB port plug compatibility would be cool.

**Comment by syssi** [comment]
I will care about.

**Comment by nutinshell** [comment]
@syssi thank you, you did a lot of great things :D

**Comment by syssi** [comment]
@nutinshell Could you check something? The the ChuangMi V1 Plug provide a temperature?

Please provide the output of

```
mirobo --ip 10.x.x.x --token a3d7fxxx  get_prop '["on","usb_on", "temperature"]'
```

**Comment by syssi** [comment]
The development branch contains the requested feature now. The device type will be detected automatically and will create two switches at Home Assistant. Once for mains the other one for the usb channel. Please give it a try.

**Comment by syssi** [comment]
@nutinshell Ping!

Could you care about this question? Thanks! :-)

https://github.com/syssi/xiaomiplug/issues/5#issuecomment-331781366

**Comment by nutinshell** [comment]
@syssi hi, sorry for the delay, just back from a very long vacation :) it works well!

**Comment by syssi** [comment]
Does the device provide a temperature? Could you test it? Just see above.

**Comment by nutinshell** [comment]
No, I can't see the temperature in mi.app
